### ISSUE TITLE
Support "Virtual"/"Pseudo" Extended Resources on a worker pool that do not trigger rollout

### ISSUE THREAD

**Issue by elankath** [gardener/gardener-extension-provider-aws#1238]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/platform aws

**What would you like to be added**:

"Virtual" or "Pseudo" extended resources specified on a worker pool - which do not represent "real" resources - should not cause a rollout of the machines of the worker pool.

### Option-1 (Naming Convention, No shoot API Change)
A "pseudo" or "virtual" resource can be disambiguated with the domain name containing the word "pseudo"/"virtual"

Example: `virtual.operator.namespace.com/memory: "2049008Ki"`

### Option-2 (Explicit delineation, Requires shoot API Change)

The `providerConfig.NodeTemplate` exposes an additional map that specify *virtual* resources of a Node that don't require rollout as opposed to *real* provisionable resources

```yaml
providerConfig:
    nodeTemplate:
        capacity:
            cpu: 123
        virtualCapacity: #PROPOSED API CHANGE
             hc.hana.com/memory: 1234567
```

**Why is this needed**:

Currently, specifying an extended resources for a worker pool in the shoot specification triggers rollout of all nodes of that worker pool.  This is not semantically in-correct since extended resources in the general case are used to represent provisionable "real" resources which should necessitate a rollout.  However, "virtual/pseudo" resources that are that represent some abstract/computational property of the Node should not trigger a rollout after the worker pool is updated.
