### ISSUE TITLE
Support assignment of multiple IPs to NAT Gateways

### ISSUE THREAD

**Issue by rnninad** [gardener/gardener-extension-provider-aws#1263]
**How to categorize this issue?**
/area control-plane
/kind enhancement
/platform aws

**What would you like to be added**:
AWS NAT Gateway allow users to assign multiple IP addresses to a NAT Gateway, which in-turn increases the NAT Gateway's capability to create more concurrent requests to a unique destination; each IP address adds 55,000 to the existing 55,000 concurrent connections limit. 

With the current configuration, we can only assign one `elasticIPAllocationID` to a NAT Gateway and not more. Kindly provide the capability to allow users to attach more elastic IPs based on their use cases. 
```
apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
kind: InfrastructureConfig
enableECRAccess: true
dualStack:
  enabled: false
networks:
  vpc: # specify either 'id' or 'cidr'
  # id: vpc-123456
    cidr: 10.250.0.0/16
  # gatewayEndpoints:
  # - s3
  zones:
  - name: eu-west-1a
    internal: 10.250.112.0/22
    public: 10.250.96.0/22
    workers: 10.250.0.0/19
  # elasticIPAllocationID: eipalloc-123456
```

**Why is this needed**:
As our solutions grow, the number of Pods increases and each Pod again has a connection pool, which further increases the number of connections to a unique destination (e.g. database, authentication service etc.); this can result in a very realistic case of a NAT Gateway hitting the 55,000 connection-limit, hence this request. 

Here's a another [AWS blog](https://aws.amazon.com/blogs/networking-and-content-delivery/attach-multiple-ips-to-a-nat-gateway-to-scale-your-egress-traffic-pattern/) further explaining a NAT Gateway's limits and the need for this feature.
