### ISSUE TITLE
Allow to specify IAM instance profiles on workers

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener-extension-provider-aws#143]
**How to categorize this issue?**

/area security
/kind api-change
/priority normal
/platform aws

**What would you like to be added**:

The ability to specify IAM instance profile on the workers. e.g. :

```yaml
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Worker
metadata:
  name: worker
  namespace: shoot--foobar--aws
spec:
  type: aws
  region: eu-west-1
  secretRef:
    name: cloudprovider
    namespace: shoot--foobar--aws
  pools:
  - name: cpu-worker
    machineType: m4.large
    machineImage:
      name: coreos
      version: 2135.6.0
    zones:
    - eu-west-1a
  providerConfig:
    apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
    kind: WorkerConfig
    volume:
      iops: 10000
    dataVolumes:
    - name: kubelet-dir
      snapshotID: snap-13234
    iamInstaceProfile:
      name: my-profile
      # arn: my-instance-profile-arn # specify either ARN or name.
```

**Why is this needed**:

This would allow to eventually (optionally) remove the extension's dependency to the IAM API, reducing the attack surface.
