### ISSUE TITLE
Add Default VolumeSnapshotClass 

### ISSUE THREAD

**Issue by runzexia** [gardener/gardener-extension-provider-aws#145]
ref https://github.com/gardener/gardener-extension-provider-gcp/issues/91

```
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: default
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: “true”
driver: ebs.csi.aws.com
deletionPolicy: Delete
```
/assign
