### ISSUE TITLE
network.vpc.gatewayEndpoints are not created when using existing VPC

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-aws#156]
**How to categorize this issue?**

/area networking
/kind bug
/priority normal
/platform aws

**What happened**:
`network.vpc.gatewayEndpoints` are now usable only when new VPC is requested (`networks.vpc.id`)

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an Infrastructure with `networks.vpc.id` and `networks.vpc.gatewayEndpoints`:

```yaml
apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
kind: InfrastructureConfig
networks:
  vpc:
    id: vpc-123456
    gatewayEndpoints:
    - s3
  zones:
  - name: eu-west-1a
    internal: 10.250.112.0/22
    public: 10.250.96.0/22
    workers: 10.250.0.0/19
```

2. Ensure that the corresponding VPC endpoint resources won't be created.

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.12.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
