### ISSUE TITLE
[AWS] Allow using existing subnets

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extension-provider-aws#3]
End-users are interested in not only using an existing VPC but also existing subnets for their AWS shoot clusters. Today, the AWS infrastructure extension always creates new, dedicated subnets (even if an existing VPC is used).

We could allow the following `InfrastructureConfig`:

```yaml
apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
kind: InfrastructureConfig
networks:
  vpc:
    id: vpc-123456 # re-use existing VPC
  zones:
  - name: eu-west-1a
    internalID: subnet-123456 # re-use existing subnet
    publicID: subnet-7890ab # re-use existing subnet
    workersID: subnet-cdefgh # re-use existing subnet
```

We could even allow a mixed setup:

```yaml
apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
kind: InfrastructureConfig
networks:
  vpc:
    id: vpc-123456 # re-use existing VPC
  zones:
  - name: eu-west-1a
    internal: 10.250.112.0/22 # create a new, dedicated subnet for internal LBs
    publicID: subnet-7890ab # re-use existing subnet
    workersID: subnet-cdefgh # re-use existing subnet
```

Constraints:

* If an existing subnet for public load balancers is used then we require that a NAT gateway + elastic IP is attached to this subnet (similar to how we require that an internet gateway is attached if an existing VPC is used)
* We keep creating dedicated route tables between the subnets.
