### ISSUE TITLE
DescribeTags constraint: Member must have length less than or equal to 20

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-aws#303]
**How to categorize this issue?**

/kind bug
/priority 3
/platform aws

**What happened**:

We observe high amount of failed Infrastructure deletions with error:

```yaml
  lastErrors:
    - description: "task \"Waiting until shoot infrastructure has been destroyed\" failed: Failed to delete Infrastructure shoot--foo--bar/bar: Error deleting infrastructure: 1 error occurred:\n\t* Failed to destroy load balancers and security groups: ValidationError: 1 validation error detected: Value '[lb1, lb2, lb2, lb3, lb4, lb5, lb6, lb7, lb8, lb9, lb10, lb11, lb12, lb13, lb14, lb15, lb16, lb17, lb18, lb19, lb20, lb21, lb22, lb23, lb24, lb25, lb26, lb27]' at 'loadBalancerNames' failed to satisfy constraint: Member must have length less than or equal to 20\n\tstatus code: 400, request id: <omitted>\n\n"
      taskID: Waiting until shoot infrastructure has been destroyed
```

Ref https://docs.aws.amazon.com/elasticloadbalancing/2012-06-01/APIReference/API_DescribeTags.html:

> Array Members: Minimum number of 1 item. Maximum number of 20 items.

**What you expected to happen**:

Infrastructure deletion should handle gracefully VPCs with more than 20 LBs.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create several Shoots that share the same VPCs
2. Create more than 20 LBs
2. Delete one of the Shoots
3. Make sure that the deletion of the Infrastructure fails with the above error

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.22.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
