### ISSUE TITLE
Add possibility to remove AZs

### ISSUE THREAD

**Issue by elpadev** [gardener/gardener-extension-provider-aws#404]
/area control-plane
/area disaster-recovery
/area networking
/kind enhancement
/priority 3

**What would you like to be added**:

Possibility to remove an Availability Zone (AZ) from a shoot cluster

**Why is this needed**:

Entering wrong AZ configuration by mistake while setting up a new cluster must be repairable, e.g. entering the same name for "zone2" and "zone3" in the `infrastructureConfig`. In productive environments, removing and creating a new cluster to correct the AZ configuration may not be possible.

Example of an `infrastructureConfig` in a `shoot.yml`:

```
infrastructureConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vpc:
          cidr: 10.250.0.0/16
        zones:
          - internal: 10.250.250.0/26
            name: ap-northeast-1a
            public: 10.250.246.0/26
            workers: 10.250.0.0/22
          - internal: 10.250.250.64/26
            name: ap-northeast-1c
            public: 10.250.246.64/26
            workers: 10.250.4.0/22
          - internal: 10.250.250.128/26
            name: ap-northeast-1c 
            public: 10.250.246.128/26
            workers: 10.250.8.0/22
```

To correct this `infrastructureConfig`, `ap-northeast-1c` must be replaced with `ap-northeast-1d` in one of the last zones.
