### ISSUE TITLE
Add validation for the `elasticIPAllocationID` field

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-aws#429]
**How to categorize this issue?**

/area quality
/kind bug
/priority 3
/platform aws

**What happened**:
Currently we miss a validation for the `elasticIPAllocationID` field which allows users to create multiple Shoots using the same `elasticIPAllocationID`. A single elastic IP allocation can be associated to single NAT gateways, hence it is not possible to create multiple Shoots with single elastic IP allocation .

**What you expected to happen**:
A proper validation to be present for the `elasticIPAllocationID` field that checks whether the elastic IP allocation is available.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an Infrastructure with Elastic IP allocation that is already associated

```yaml
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vpc:
          cidr: 10.222.0.0/16
        zones:
          - internal: 10.222.112.0/26
            name: eu-west-1a
            public: 10.222.96.0/26
            workers: 10.222.0.0/26
            elasticIPAllocationID: eipalloc-0645b3aa03c712345
```

2. Make sure that the creation fails and leaves a NAT gateways in failed state

```
aws_nat_gateway.natgw_z0: Creating...
aws_nat_gateway.natgw_z0: Still creating... [10s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [20s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [30s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [40s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [50s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [1m0s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [1m10s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [1m20s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [1m30s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [1m40s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [1m50s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [2m0s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [2m10s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [2m20s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [2m30s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [2m40s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [2m50s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [3m0s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [3m10s elapsed]
aws_nat_gateway.natgw_z0: Still creating... [3m20s elapsed]

Error: Error waiting for NAT Gateway (nat-0d20caf4a296f12345) to become available: unexpected state 'failed', wanted target 'available'. last error: %!s(<nil>)

  on tf/main.tf line 218, in resource "aws_nat_gateway" "natgw_z0":
 218: resource "aws_nat_gateway" "natgw_z0" {
```

When we check the underlying NAT gateway, we see the reason for the failed creation
```
            "FailureCode": "Resource.AlreadyAssociated",
            "FailureMessage": "Elastic IP address [eipalloc-0645b3aa03c712345] is already associated",
```

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.29.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
