### ISSUE TITLE
`aws-custom-route-controller` gets enabled on Shoot creation and gets removed in the subsequent Shoot reconciliation 

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-aws#619]
**How to categorize this issue?**

/area control-plane
/kind bug
/platform aws
/priority 1

**What happened**:
On Shoot creation the `ControlPlane` gets mutated with:

```yaml
    providerConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      cloudControllerManager:
        useCustomRouteController: true
```

On a subsequent Shoot reconciliation, the gardenlet sets again the providerConfig field and the `ControlPlane` is reverted to:

```yaml
    providerConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
```

and the `aws-custom-route-controller` gets disabled again.

The issue is also described in https://github.com/gardener/gardener/issues/6703#issuecomment-1257733490.

**What you expected to happen**:
Not the above one.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant): `v1.38.1`
- Extension version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
