### ISSUE TITLE
Shoot gets created with overlay network disabled and in subsequent reconciliation overlay network gets enabled

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-aws#621]
**How to categorize this issue?**

/area control-plane
/kind bug
/platform aws
/priority 1

**What happened**:
Similar to https://github.com/gardener/gardener-extension-provider-aws/issues/619:

On Shoot creation the `Network` gets created with:
```yaml
  spec:
    podCIDR: 100.64.0.0/12
    providerConfig:
      apiVersion: calico.networking.extensions.gardener.cloud/v1alpha1
      backend: none
      ipv4:
        mode: Never
      kind: NetworkConfig
    serviceCIDR: 100.104.0.0/13
    type: calico
```

After reconciliation the providerConfig gets removed.
```yaml
  spec:
    podCIDR: 100.64.0.0/12
    serviceCIDR: 100.104.0.0/13
    type: calico
```

**What you expected to happen**:
Not the above one.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version: `v1.38.1`
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
