### ISSUE TITLE
Introduce `zone` label on the MachineClass. 

### ISSUE THREAD

**Issue by hardikdr** [gardener/gardener-extension-provider-aws#77]
**What would you like to be added**:  We recently introduced the scale-to-zero feature for the cluster-autoscaler. This feature requires the autoscaler to know the `zone` for which the MachineClass/MachineDeployment is being created as part of its sub-functionality. Following are the related discussions/issues: 
- https://github.com/gardener/autoscaler/pull/26#discussion_r365868415
- https://github.com/gardener/autoscaler/issues/34

It would mean, autoscaler can't scale-up from zero for statefulset workload. 

Also to note, we plan to re-work on the architecture of the scale-to-zero feature. There we may add `zone` field in the AWSMachineClass's Spec. But the approach there has to be completely finalized yet.

**Comment by rfranzke** [comment]
Can you please share an example of such an `AWSMachineClass`? How should it look like?

**Comment by hardikdr** [comment]
Something like this would be nice:
```
apiVersion: machine.sapcloud.io/v1alpha1
kind: AWSMachineClass
metadata:
  name: awsmachineclass
  labels:
    failure-domain.beta.kubernetes.io/zone: eu-west-1b
spec:
  ami: ami-12345
..
```
